image: ubuntu:focal

build:
  stage: build
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq -y install gcc-aarch64-linux-gnu build-essential bison flex python3 python3-distutils python3-dev swig make python python-dev bc
  script:
    - export CROSS_COMPILE=aarch64-linux-gnu- && export ARCH=arm64
    - make nintendo-switch_defconfig
    - make -j$(nproc)
  artifacts:
    paths:
      - u-boot.elf

